# Generated by Django 5.0.4 on 2024-04-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_caregory_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=21.54, on_delete=django.db.models.deletion.CASCADE, to='article.caregory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
